travis:
  secure:
    BINSTAR_TOKEN: eciDlI1fWwZB0C7jGwR6Ksa9FMdM7Tfa+s5bWZESodnB2DdnDgZKiMyO6y3c4HWHbxsHvxNFhBCVag9QoukU3kXaUUWFCRQCbNxfutf6RNp3G0YeNjVfMZ56kGhUdF98+A/P16cG1+P9DvpVMhq4LvNEEImS8+Cv7Xp8WlDORI38k9gM/Nr+KMkC1Bb58xUdsfe5rXYmjbcR43t6NznhmRBnuZk+EHrjVBHP5bRg1wQhrGzXNfW2XQkZgTVigMcbpXlw2bJPgMsB7Lzh0GWU5QZwblLPnxdIlILBBa+uXmIB7rYvSvFm5MqCRbaEM8/pYLsA38pq3xkOYNHsvTSKWSstVuzmuvloygSaDwiuFTpsPZ1+v8bBE4/3C31GsqoglZ0jcNgM6S0by7e3kesiiIXKdJ4XLTFHwh7zfM13CDO9gbXl/J4chjuSgcExPkR3Hx/0ZvgYKqEqJS4+Er+iDtowaPAJYwCqfRqAAZg+g1/e/phA5ZeTrTqOfn4LDju4CY2yh/F2wWBlfnmWq0KgxdvFLlHyoJnEvspePfVqq+sfKMFfkU1Rcd5Bi8ZUSTdKON4ZMr4L8yCk5yUY/FzrQaD6a0TItpcEtGpIZFTlpVbVVubhGN2Bp84qQR/eLcwcve8zW/nx5FtapVp+T+Ms5SdR1Mt62hmI3Wlv0XJ+3Kk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
